---
- name: remove zram-generator to disable swap
  dnf:
    name: zram-generator
    state: absent

- name: load br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: enable to bridge
  copy:
    src: sysctl.d/k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: disable nftables
  command: update-alternatives --set iptables /usr/sbin/iptables-legacy

- name: disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: disable selinux
  command: sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

- name: register k8s repository
  copy:
    src: yum.repos.d/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: install kube tools
  dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: enable kubelet
  systemd:
    name: kubelet
    enabled: yes
