---
- name: install prerequisite packages of docker(apt)
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: yes

- name: add docker repository gpg key(apt)
  apt_key:
    url: https://download.docker.com/linux/{{ apt_distribution_id }}/gpg
    state: present

- name: add docker repository(apt)
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ apt_distribution_id }} {{ apt_os_distribution }} stable"
    state: present

- name: install docker(apt)
  apt:
    name:
      - docker-ce={{ docker_version_apt }}
      - docker-ce-cli={{ docker_version_apt }}
      - containerd.io={{ containerd_io_version_apt }}
    update_cache: yes
  notify: restart docker
...
