---
- import_tasks: apt.yml
  when: "ansible_pkg_mgr == 'apt'"
- import_tasks: yum.yml
  when: "ansible_pkg_mgr == 'yum'"
- import_tasks: dnf.yml
  when: "ansible_pkg_mgr == 'dnf'"

- name: enable docker
  systemd:
    name: docker
    enabled: yes

- name: add current user to docker group
  user:
    name: "{{ ansible_ssh_user }}"
    append: yes
    groups: docker
    state: present
...
